[build]
  publish = "public"
  command = "echo 'EspoCRM deploy preview (Netlify not supported)'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"

[edge_functions]
  directory = "netlify/edge-functions"

[[redirects]]
  from = "/*"
  to = "/netlify-not-supported.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    "Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
    "X-Content-Type-Options" = "nosniff"
    "Referrer-Policy" = "strict-origin-when-cross-origin"
    "X-Frame-Options" = "DENY"

[[edge_functions]]
  path = "/*"
  function = "netlify-notice"
