[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  functions = "netlify/functions"

[edge_functions]
  directory = "netlify/edge-functions"

[[redirects]]
  from = "/status"
  to = "/.netlify/functions/status"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/netlify-not-supported.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    "Strict-Transport-Security" = "max-age=63072000; includeSubDomains; preload"
    "X-Content-Type-Options" = "nosniff"
    "Referrer-Policy" = "strict-origin-when-cross-origin"
    "X-Frame-Options" = "DENY"

[[headers]]
  for = "/netlify-not-supported.html"
  [headers.values]
    "Cache-Control" = "no-cache, no-store, must-revalidate"

[[edge_functions]]
  path = "/netlify-not-supported.html"
  function = "netlify-notice"
